#!/usr/bin/env bash
# This script transfers a file from a client to a server using SCP.

# Display usage message if less than 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Transfer the file to the user's home directory on the server using SCP
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check if SCP command was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
