#!/usr/bin/env bash
# This script displays a list of currently running processes with hierarchy.

# Display process information in a user-oriented format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | head -50
