#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file.

# Use a while loop to read each line from /etc/passwd
while IFS=: read -r username _ uid gid gecos home_dir shell; do
    # Display the story for each user
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $gecos"
done < /etc/passwd
